Repository openshift/csi-driver-manila-operator, pull requests merged in 2020-08, with the labels that each got.

#45 Change operand namespace
  assets/controller.yaml
  assets/controller_sa.yaml
  assets/node.yaml
  assets/node_nfs.yaml
  assets/node_sa.yaml
  assets/rbac/controller_privileged_binding.yaml
  assets/rbac/node_privileged_binding.yaml
  assets/rbac/provisioner_binding.yaml
  assets/rbac/snapshotter_binding.yaml
  manifests/09_credentials.yaml
  pkg/controllers/manila/manila.go
  pkg/controllers/secret/secretsync.go
  pkg/generated/bindata.go
  pkg/operator/starter.go
  pkg/util/const.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#47 Remove ManilaControllerAvailable condition
  pkg/controllers/manila/manila.go
Labels: approved, lgtm

#48 Update to latest library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontroller/csi_driver_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontroller/sync.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/modules.txt
Labels: approved, lgtm

#46 Bug 1863056: Allow the driver to run on any node
  assets/node.yaml
  assets/node_nfs.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#49 Bug 1867735: Fix sync of openshift-config/cloud-provider-config ConfigMap
  manifests/05_clusterrole.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#51 Bug 1869504: base storageclass names on lower case
  pkg/controllers/manila/manila.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#50 Bug 1869585: Fix log level of NFS CSI driver
  assets/node_nfs.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#53 Add missing assets
  assets/credentials.yaml
  assets/namespace.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm
