Repository openshift/csi-driver-manila-operator, pull requests merged in 2020-09, with the labels that each got.

#56 Bug 1871999: Allow controller and DaemonSets to run on master nodes
  assets/controller.yaml
  manifests/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#57 Bug 1868339: Don't create CredentialsRequest in Manila CSI Driver Operator
  assets/credentials.yaml
  pkg/generated/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#58 Bug 1868339: Use the CredentialsRequest created by CVO
  pkg/controllers/secret/secretsync.go
  pkg/operator/starter.go
  pkg/util/const.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#60 Bug 1876791: Update RBAC of the external-provisioner
  assets/rbac/provisioner_role.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#52 Bug 1869590: base storageclass names on lower case
  pkg/controller/maniladriver/manila_storageclasses.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#61 Bug 1878980: Use hostNetwork for the NFS CSI driver
  pkg/controller/maniladriver/nfs_nodeplugin.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#64 Bug 1880896: Replace cert authority path from clouds.yaml
  assets/controller.yaml
  pkg/controllers/secret/secretsync.go
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#65 Bug 1883018: Fix location of node plugin cacert file
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#66 Bug 1879475: Update library-go to include explicit reasons
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#67 Include huffmanca as an approver
  OWNERS
Labels: approved, lgtm
