Repository openshift/csi-driver-manila-operator, pull requests merged in 2021-01, with the labels that each got.

#74 go.mod: Remove unused dependencies
  go.mod
  go.sum
Labels: approved, lgtm

#73 Bug 1820238: add metadata with cluster ID to generated storage classes
  go.mod
  go.sum
  pkg/controllers/manila/manila.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#77 Bug 1915643: revert setting metadata in the storage classes
  pkg/controllers/manila/manila.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#81 Bug 1917587: disable Manila operator in case of 403 error
  pkg/controllers/manila/manila.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#82 Bug 1918140: Fix sync of config.openshift.io informer
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#85 Bug 1918716: increase Keystone timeout to 2 minutes
  pkg/controllers/manila/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#87 [release-4.6] Bug 1921599: Add "openshift.io/node-selector" annotation to namespace
  assets/namespace.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#84 Bug 1917587: disable Manila operator in case of 404 error
  pkg/controllers/manila/manila.go
  pkg/controllers/manila/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
