Repository openshift/csi-driver-manila-operator, pull requests merged in 2022-10, with the labels that each got.

#156 Bug 2057637: Include secrets to VolumeSnapshotClass
  assets/volumesnapshotclass.yaml
Labels: lgtm, ok-to-test, bugzilla/valid-bug, approved, bugzilla/severity-medium

#158 Ensure files follow go 1.19 formatting
  pkg/controllers/manila/manila.go
Labels: lgtm, approved

#159 OCPBUGS-1904: Only deploy VolumeSnapshotClass when CRD exists
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/severity-critical
