Repository openshift/csi-driver-manila-operator, pull requests merged in 2023-08, with the labels that each got.

#184 OCPBUGS-14049: Don't cache OpenStack client
  pkg/controllers/manila/manila.go
  pkg/controllers/manila/openstack.go
  pkg/operator/starter.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#193 Remove unused Dockerfile.openshift.ci file
  build/Dockerfile.openshift.ci
Labels: lgtm, approved

#188 OCPBUGS-8067: Fix SCC admission failure race during initial deployment
  pkg/operator/starter.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#198 STOR-1440: Restart controller Pods if metrics-serving-cert changed
  pkg/operator/starter.go
Labels: lgtm, approved, jira/valid-reference

#191 Configure User Agent
  pkg/controllers/manila/openstack.go
Labels: lgtm, approved
