Repository openshift/csi-driver-manila-operator, pull requests merged in 2023-03, with the labels that each got.

#173 OCPBUGS-8628: Bump go.mongodb.org/mongo-driver to v1.5.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/valid-reference

#175 OCPBUGS-8683: Add management workloads annotations
  assets/controller.yaml
  assets/node.yaml
  assets/node_nfs.yaml
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#176 OCPBUGS-10556: Bump go.mongodb.org/mongo-driver to v1.5.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, bugzilla/valid-bug, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#177 OCPBUGS-10605: Bump go.mongodb.org/mongo-driver to v1.5.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, bugzilla/valid-bug, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
